# Generated by Django 4.1.2 on 2022-10-31 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='username',
            field=models.CharField(default=1, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='2자 이상 입력해주세요..!')], verbose_name='유저이름'),
            preserve_default=False,
        ),
    ]
