# Generated by Django 4.1.4 on 2022-12-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normaluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='username',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='name',
            field=models.CharField(default=1, max_length=6, verbose_name='name'),
            preserve_default=False,
        ),
    ]
