# Generated by Django 4.1.4 on 2022-12-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitThumCoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coin_symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bithum_coin_list',
            },
        ),
        migrations.CreateModel(
            name='CoinSymbolCoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coin_symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'coin_symbol',
            },
        ),
        migrations.CreateModel(
            name='SearchBurketCoinIndexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'burket_coin_list',
            },
        ),
        migrations.CreateModel(
            name='UpbitCoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('k_name', models.CharField(default='', max_length=50)),
                ('e_name', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=15)),
                ('market_warning', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'upbit_coin_list',
            },
        ),
    ]
