# Generated by Django 4.1.2 on 2022-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInforamtionally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField(verbose_name='가격')),
                ('start_price', models.BigIntegerField(verbose_name='시작가')),
                ('end_price', models.BigIntegerField(verbose_name='종가')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coin',
            },
        ),
        migrations.CreateModel(
            name='DataInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealstateInformationlly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, verbose_name='지역')),
                ('price', models.BigIntegerField(verbose_name='가격')),
            ],
            options={
                'db_table': 'real',
            },
        ),
        migrations.CreateModel(
            name='StockInformationally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField(verbose_name='가격')),
                ('start_price', models.BigIntegerField(verbose_name='시작가')),
                ('end_price', models.BigIntegerField(verbose_name='종가')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
