# Generated by Django 4.1.4 on 2022-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBurketCoinIndexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'burket_coin_list',
            },
        ),
    ]
