# Generated by Django 4.1.4 on 2022-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_upbitcoinlist_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitThumCoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coin_symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bitthum_coin_list',
            },
        ),
    ]
