# Generated by Django 4.1.4 on 2022-12-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coininforamtionally_market_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coininforamtionally',
            name='k_name',
        ),
        migrations.RemoveField(
            model_name='coininforamtionally',
            name='market_name',
        ),
        migrations.RemoveField(
            model_name='stockinformationally',
            name='k_name',
        ),
        migrations.RemoveField(
            model_name='stockinformationally',
            name='market_name',
        ),
    ]
