# Generated by Django 4.1.4 on 2022-12-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_coininforamtionally_k_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coininforamtionally',
            name='market_warning',
        ),
    ]
